spring:
  application:
    name: hello-service #应用名称
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/, http://localhost:1112/eureka/
